module.exports = {
	CREEP_DEFENCE:"DEFENCE",
	CREEP_OFFENCE:"OFFENCE",
	CREEP_WORKER:"WORKER",
	CREEP_HARVESTER:"HARVESTER",

	STATE_AMASS:"AMASS",
	STATE_CHECK:"CHECK",
	STATE_DEFENCE:"DEFENCE",
	STATE_STORE:"STORE",
	STATE_EXPAND:"EXPAND",
	STATE_SPREAD:"SPREAD"
}